# Generated by Django 5.1.6 on 2025-06-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="owner",
            new_name="user",
        ),
    ]
