# Generated by Django 5.1.6 on 2025-06-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_owner_board_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="name",
            new_name="title",
        ),
    ]
